### ISSUE TITLE
wish: more documentation

### ISSUE THREAD

**Issue by markstos** [olalonde/connect-csrf-cookie#1]
CSRF vulnerabilities are enabled because of cookie authentication. Yet the fix described here is to set a cookie.

Some further docs could help clarify why this helps.  Perhaps the idea is that the CSRF cookie is one-time use. However, nothing in the code here has explicit expiry time, so it's not clear from an initial code read how long the cookie set here is intended to persist.

**Comment by olalonde** [comment]
I wrote this a long time ago and I'm not sure exactly why but I think the idea is to read the token from cookie and use it in AJAX requests as a query parameter or body field. The server should never read the token from cookies however. There's a more elaborate explanation on StackOverflow http://stackoverflow.com/questions/20504846/why-is-it-common-to-put-csrf-prevention-tokens-in-cookies

**Comment by olalonde** [comment]
Added link to README.
